#!/usr/bin/bash

echo "This is our first script"

# Exit statuses can have any value from 0 - 255
# Exit code 0 indicates that the script has executed succesfully
# Any non zero exit code indicates that something went wrong
#          https://tldp.org/LDP/abs/html/exitcodes.html

exit 0
